### ISSUE TITLE
Bug in C# Implementation of Z-Normalize Function: Incorrect Vector Indexing

### ISSUE THREAD

**Issue by SirCollypso** [ISUE/Jackknife#1]
### Description
I've found a bug in the C# implementation of the `ZNormalize` function in the `Mathematics.cs` file. The current implementation incorrectly indexes the `points` Vector, leading to an error in the normalization process. The corresponding C++ and JavaScript implementations of this function are correct.

### Location of the Bug
- **C# Implementation:** [Mathematics.cs#L66](https://github.com/ISUE/Jackknife/blob/ac4022c526d471cb997a670c4b43485a126bd68e/csharp/Jackknife/Mathematics.cs#L66)

### Current C# Implementation
```csharp
points[i] = (points[1] - mean) / var;
```

### Expected C# Implementation
```csharp
points[i] = (points[i] - mean) / var;

**Comment by crpittman** [comment]
Thanks for finding this. I have pushed a fix addressing the issue as described.
